version: '3.8'

services:
  upload-server:
    image: mayth/simple-upload-server:latest
    command: [
      "-token", "${UPLOAD_SERVER_TOKEN:-uploadtoken}",
      "-cert", "/var/run/secrets/upload-server-cert",
      "-key", "/var/run/secrets/upload-server-key",
      "-tlsport", "443",
      "-port", "80",
      "-upload_limit", "805306368",  # 768MB
      "/var/data/"
    ]
    volumes:
      - ./uploaded-data/:/var/data/
    secrets:
      - upload-server-cert
      - upload-server-key

  urllib3-client:
    build:
      dockerfile: Dockerfile
      context: .
    cap_add:
      # So that "tc" can be used to slow down outbound network traffic
      - NET_ADMIN
    volumes:
      - ./data-for-upload/:/var/data-for-upload/
      - .:/home/

secrets:
  upload-server-cert:
    file: secrets/server-crt.pem
  upload-server-key:
    file: secrets/server-key.pem
